base_url = "https://davidchen.io"

title = "David Chen"
description = "David Chen is a software engineer living in the San Francisco Bay Area."

# Enable Sass.
compile_sass = true

# Don't build search index.
build_search_index = false

# Generate Atom feeds.
generate_feed = true
feed_filename = "atom.xml"

# Enable syntax highlighting.
[markdown]
highlight_code = true
highlight_theme = "inspired-github"

[extra]
name = "David Chen"
email = "me@davidchen.io"
github_id = "davidcgl"
github_url = "https://github.com/davidcgl"
linkedin_id = "davidcgl"
linkedin_url = "https://www.linkedin.com/in/davidcgl"
twitter_id = "@archenary"
twitter_url = "https://twitter.com/archenary"
